services:
  php:
    build:
      context: ./php
      args:
        HOST_IP: ${HOST_IP}
      dockerfile: Dockerfile.${DIST}
    volumes:
      - ${APP_DIR}:/app
      - composer_cache:/root/.composer/cache
    working_dir: /app

  nodejs:
    image: node:latest
    volumes:
      - ${APP_DIR}:/app
    working_dir: /app

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.${WEB_SERVER}
      args:
        - PUBLIC_DIR
    volumes:
      - ${APP_DIR}:/app
    working_dir: /app
    ports:
      - "8000:80"
      - "4430:443"

  db:
    image: postgres:17.3
    shm_size: 1g # Increase as needed.
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "54320:5432"

  redis:
    image: redis:7.4
    ports:
      - "63790:6379"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "10250:1025"
      - "8020:8025"

volumes:
  db_data:
  composer_cache:
