name: Build Docker containers

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos-stream-9, ubuntu-20.04, ubuntu-24.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.os }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Generate .env file
        run: |
          echo "APP_DIR=./app" > .env
          echo "PUBLIC_DIR=/public" >> .env
          echo "DIST=${{ matrix.os }}" >> .env
          echo "WEB_SERVER=apache" >> .env

      - name: Build Docker containers
        run: |
          docker compose --env-file .env -f docker-compose.yml build
          docker compose --env-file .env -f docker-compose.yml up -d

      - name: Stop and clean up Docker containers
        run: |
          docker compose --env-file .env -f docker-compose.yml down
